name: uniodontopoa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  qr_flutter: ^4.1.0
  flip_card: ^0.7.0
  intl: ^0.19.0
  flutter_pdfview: ^1.3.2
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  file_picker: ^8.0.0  
  permission_handler: ^11.0.1
  mask_text_input_formatter: ^2.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# Configuração do ícone do app
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#A60069" # Vinho médio Uniodonto
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#A60069"
    theme_color: "#A60069"

# Configuração da Splash Screen
flutter_native_splash:
  color: "#FFFFFF" # Fundo branco
  image: assets/icon/app_icon.png
  branding_mode: bottom
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  
  # Assets (imagens, fonts, etc.)
  assets:
    - assets/images/Logo-na-horizontal-colorido.png
    - assets/images/Logos-Uniodonto-POA2.png
    - assets/images/logo renova.png
    - assets/images/logo urgencia.png
    - assets/images/logo suporte.png
    - assets/icon/ # Pasta para os ícones do app
    - assets/icon/PIN-Uniodonto.png
    
  fonts:
    - family: Georama
      fonts:
        - asset: assets/fonts/static/Georama-Regular.ttf
        # Adicione outros pesos da fonte Georama se tiver:
        # - asset: assets/fonts/static/Georama-Bold.ttf
        #   weight: 700
        # - asset: assets/fonts/static/Georama-Medium.ttf
        #   weight: 500
        # - asset: assets/fonts/static/Georama-Light.ttf
        #   weight: 300
